spring.application.name=otp-bank

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

app.values.max-cards-value=3

#В prod. закинуть в env
app.security.jwt.secret=${APP_SECURITY_JWT_SECRET:dev-secret-key-for-otp-bank-jwt-signing-1234567890}
app.security.jwt.access-token-ttl-minutes=${APP_SECURITY_JWT_ACCESS_TOKEN_TTL_MINUTES:15}
app.security.jwt.refresh-token-ttl-days=${APP_SECURITY_JWT_REFRESH_TOKEN_TTL_DAYS:365}

logging.file.name=logs/log.log
