spring.application.name=otp-bank

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/bank
spring.datasource.username=postgres
spring.datasource.password=postgres

app.values.max-cards-value=3

#В prod. закинуть в env
app.security.jwt.secret=dev-secret-key-for-otp-bank-jwt-signing-1234567890
app.security.jwt.access-token-ttl-minutes=15
app.security.jwt.refresh-token-ttl-days=365

logging.file.name=logs/log.log
